sudo: false
language: node_js
node_js:
  - "stable"
script: "./etc/build.sh"
env:
  global:
    secure: "GUHClO6u/VQak2U2sXZbXyhKTjwFNNDXf+Lyz6ag85eI0/m2Rm1ABg3+jFfBMZjrUJ4s6Alc7IGEzX3vXl0hTsUbHfAy3zBjwZQ6Y7lLScb4ZPIYMEryyEDqjjlHxrtoCs73XCGT7KsGh5a/0MDXw6PHdKziB5QJtibJcMrXfXE="
notifications:
  email: false